### ISSUE TITLE
Update catalog page

### ISSUE THREAD

**Issue by RachL** [datafoodconsortium/prototype#113]
## Description
**- As a:** producer
**- On page:** http://proto.datafoodconsortium.org/#/x-catalog-supply
**- I want to be able to do:** 

- [x] Main menu: remove text "MonCatalog"
- [x] See a page title "Product catalog"
- [x] Add a placeholder in the search bar saying "Search by name" => provided it's by name we can search, I'm not 100% sure doing my tests
- [x] Change the "create" action icon which symbolizes "upload" currently by something like https://www.streamlinehq.com/icons/streamline-mini-line?search=create and add a tooltip on the button that says create
- [x] Add a tool tip on 
![image](https://user-images.githubusercontent.com/6525576/232521219-069598f4-80f9-47e4-8b59-02f1a77c51a8.png)
 which says "Edit links"
 
 - [x] Add a tooltip on 
![image](https://user-images.githubusercontent.com/6525576/232521403-07d1e911-911b-46dc-964f-e150573f332f.png)
which says "Edit product"

- [x] All columns headers should have a first letter capitalized

- [x] First column should be the Name of the product

- [x] If quick, align height of the icon and height of the search field

![image](https://user-images.githubusercontent.com/6525576/232522424-6061e6ad-04db-4bcd-8782-bd085b8abc42.png)

## Acceptance Criteria & Tests

See checklist above.

When done we should have a page looking UX-wise like:

![image](https://user-images.githubusercontent.com/6525576/232524523-9a791e69-94f2-40ea-b31b-ecc44bfd78c0.png)

**Comment by Mikoteko** [comment]
On branch improveErgonomics https://github.com/datafoodconsortium/prototype/tree/improveErgonomics
