### ISSUE TITLE
Update product edit page

### ISSUE THREAD

**Issue by RachL** [datafoodconsortium/prototype#114]
## Description

**- As a:** producer
**- On page:** e.g. http://proto.datafoodconsortium.org/#/x-item-supply-platform/https%3A%2F%2Fdemo.socleo.org%2Fapi%2Fdfc%2FcatalogItem%2F1382544797143 

**- I want to be able to do:** 

- [x] See product name as title of the page

- [x] See producer name below and then the rest of the field as table: combine catalogitem and supply product for now, we can add offers in another issue

- [x] "Update data at source platform or refresh from it" should be replace by [this icon](https://www.streamlinehq.com/icons/streamline-mini-line?search=save) with tooltip "Save changes on source platform"

- [x] "Refresh data from platform" should be replaced by [this icon](https://www.streamlinehq.com/icons/streamline-mini-line?search=refresh) with tooltip "Update data with source platform"

- [x] Remove "test API sameAs" unless @simonLouvet has a use case for it

- [ ]  Add every field provided in the screenshot below
     - [x] Magnesium ( dfc-b:hasNutrientCharacteristic)
     - [x] Weight (dfc-b:hasPhysicalCharacteristic)
     - [x] Origin (dfc-b:hasGeographicalOrigin)
     - [x] Label:certification (hascertification et hasClaim)
     - [x] Url sur chaque plateforme source
     - [x] Allergens (dfc-b:hasAllergenCharacteristic)
     - [x] Product name (dfc:name sur la classe DFC_Subject)
     - [ ] Producer name (relations "requests", "proposes", "supplies" depending on FunctionalProduct, TechnicalProduct and SuppliedProduct)
 
- [ ] Change ontology
    - [x]  Create Product Name
    - [x]  Change Magnesium unit to gram in supply product 1
    - [ ]  Add Producer name
    - [x]  Allergens -> multiple ones + pb solved

- [x] Make multiple arrays with the magnesium/allergens/certification ? 

- [ ] Tests on every product (Socleo + ontology)

## Acceptance Criteria & Tests

See checklist above.

When done we should have a page looking UX-wise like:

![image](https://user-images.githubusercontent.com/6525576/233130836-c75e0906-88f4-440f-b70e-74ff0e2de8b1.png)

**Comment by Mikoteko** [comment]
@simonLouvet wants to keep the "test API sameAs" for the moment, as it is currently used for tests. We can improve the ergonomics of it if needed (hiding it or making it smaller?)

**Comment by Mikoteko** [comment]
The data for the weight, magnesium, allergens need to be imported first (datanodes). For the origin and the label/certification we only get ids for the moment (such as dfc-f:CentreValLoire or dfc-Label1)

**Comment by Mikoteko** [comment]
Problem with the property hasUnit with the Magnesium in ontology 1.7.0 in Supply Product 1 -> weight -> <dfc-m:Gram> instead of <http://static.datafoodconsortium.org/data/measures.rdf#Gram>

**Comment by Mikoteko** [comment]
Problem with the allergens -> the unit doesn't exist 

![Image](https://github.com/datafoodconsortium/prototype/assets/63355855/8e3abc35-aa6e-4dc7-b5e4-ce7db523ea32)

**Comment by Mikoteko** [comment]
What do we mean by "Label?" in Label:Certification?
