### ISSUE TITLE
Make scrolling work only inside pages

### ISSUE THREAD

**Issue by RachL** [datafoodconsortium/prototype#115]
## Description
**- As a:** prototype user
**- On page:** all pages
**- I want to be able to do:** scroll inside page without loosing left menu and tables header from sight

## Acceptance Criteria & Tests

1. When visiting pages like http://proto.datafoodconsortium.org/#/x-catalog-supply
2. I want to be able to scroll within the table and not on the whole page: left menu and table headers should be visible no matter which line of the table I'm looking at

**Comment by RachL** [comment]
Might be blocked by #111

**Comment by Mikoteko** [comment]
Problem solved with #111
