### ISSUE TITLE
[WIP] Order listing

### ISSUE THREAD

**Issue by RachL** [datafoodconsortium/prototype#116]
## Description
**- As a:** testDFC producer 
**- On page:** new page `/orders`
**- I want to be able to do:** See a list of orders containing my products across all platform

If the order contains product from different products as well, I should not see other producers' data. Only mine.

## WIP Mockups

![image](https://user-images.githubusercontent.com/6525576/234034487-ebb4ad97-49eb-49a6-acae-4e17cc957639.png)

## Acceptance Criteria & Tests

TODO

**Comment by RachL** [comment]
@Alcoz @RaggedStaff @lecoqlibre I have a few questions about orderlines before I can finish this issue for the prototype.

- an orderline can have a weight different than the weight displayed in the catalog (cases of products like cheese, meat...) : was this taken into account in v1.8?

- I see sale sessions are linked to shipping and pickup methods  by quantities. Am I correct to say that quantity refers to the number of shipping options available through that sale session?

- beside customer categories and addresses I don't see anything else describing the customer. Can we add the name, email and maybe phone number or was there a reason to leave it aside? I know OFN for example will hide these details from producers in some cases for privacy issues or competitive ones (some hubs don't want their producers to have direct contact with customers). But there is a setting in the platform to allow producers to see them. So when the permission is not given, OFN returns the field with "hidden" in value, otherwise info is shown. And in case of delivery it can be useful to be able to contact the customer.

**Comment by Alcoz** [comment]
- An "Orderline" has a relation "hasQuantity" linked to a "QuantitativeValue" where a unit can be attached
- I don't understand your comment as SaleSession are linked to "ShippingOption" by relation "hasOption". However, I don't understand why there is a relation "quantity" on "SaleSession" and on "ShippingOption". For me, it could be removed.
- A customer is an agent that orders something. The class "Agent" have almost all the information you ask, I just see that an enterprise don't have a name.

**Comment by RachL** [comment]
@Alcoz @RaggedStaff @lecoqlibre @simonLouvet @sankarom My notes from our discussion yesterday:

- we need to update the ontology to add weight on products
- this affects both products sold by weight/volume and by unit/item as it can be usefull for logistics
- @Alcoz will organize a meeting when he is back in August to organize this change
- @simonLouvet will wait for this ontology update before updating the prototype

**Comment by simonLouvet** [comment]
5J
