### ISSUE TITLE
Check if the code for the DataGrids in x-item-supply-platform is ok with Simon

### ISSUE THREAD

**Issue by Mikoteko** [datafoodconsortium/prototype#119]
I put the nutrients, physical characteristics and allergens in Datagrid inside the file itemSupplyPlatform/model.js

What the Datagrids look like for the moment
![Image](https://user-images.githubusercontent.com/63355855/239954945-77974e61-e4f8-4e40-8dc6-2ff63b021a00.png)

For the code, I used a generic function setDataGrid (used for the generation of the nutrients, allergens.. Datagrids)
The function is called 3 times in the method setData

![Image](https://user-images.githubusercontent.com/63355855/239955191-588a9d81-852c-4d8f-8adf-b7e911a1fdac.png)

![Image](https://user-images.githubusercontent.com/63355855/239955385-7638904f-4b35-4bf8-8dc2-f3c3e2b606ba.png)

**Comment by RachL** [comment]
@simonLouvet can we close this one?
